//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_edit
    {
        public int auid { get; set; }
        public string style { get; set; }
        public string prj { get; set; }
        public string staff { get; set; }
        public string editor { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
    
        public virtual PrjData PrjData { get; set; }
        public virtual V_Empdata V_Empdata { get; set; }
        public virtual V_Empdata V_Empdata1 { get; set; }
    }
}
