//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthData
    {
        public MonthData()
        {
            this.PrjData = new HashSet<PrjData>();
            this.PrjData1 = new HashSet<PrjData>();
            this.Worksheet = new HashSet<Worksheet>();
        }
    
        public int MonthPK { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public Nullable<int> Week { get; set; }
    
        public virtual ICollection<PrjData> PrjData { get; set; }
        public virtual ICollection<PrjData> PrjData1 { get; set; }
        public virtual ICollection<Worksheet> Worksheet { get; set; }
    }
}
