//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Empdata
    {
        public V_Empdata()
        {
            this.PrjData = new HashSet<PrjData>();
            this.Login_auth = new HashSet<Login_auth>();
            this.audit_edit = new HashSet<audit_edit>();
            this.audit_edit1 = new HashSet<audit_edit>();
            this.Worksheet = new HashSet<Worksheet>();
            this.Worksheet1 = new HashSet<Worksheet>();
        }
    
        public string EmpID { get; set; }
        public string Unit { get; set; }
        public string Section { get; set; }
        public string CN_Name { get; set; }
        public string EN_Name { get; set; }
        public string Email { get; set; }
        public string Pwd { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<PrjData> PrjData { get; set; }
        public virtual ICollection<Login_auth> Login_auth { get; set; }
        public virtual ICollection<audit_edit> audit_edit { get; set; }
        public virtual ICollection<audit_edit> audit_edit1 { get; set; }
        public virtual ICollection<Worksheet> Worksheet { get; set; }
        public virtual ICollection<Worksheet> Worksheet1 { get; set; }
    }
}
