//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workload.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkloadEntities1 : DbContext
    {
        public WorkloadEntities1()
            : base("name=WorkloadEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<audit_edit> audit_edit { get; set; }
        public virtual DbSet<budget_plan> budget_plan { get; set; }
        public virtual DbSet<Login_auth> Login_auth { get; set; }
        public virtual DbSet<MonthData> MonthData { get; set; }
        public virtual DbSet<PrjData> PrjData { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Worksheet> Worksheet { get; set; }
        public virtual DbSet<V_Empdata> V_Empdata { get; set; }
    }
}
